name: 'Bulid Test'
on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v2
        with:
          registry-url: "https://registry.npmjs.org"
          node-version: '19.9.0'
      - name: Package install
        run: yarn
      - name: Build Test
        run: yarn run build
