name: Production PR Open

on:
  pull_request:
    branches: [ master, main ]

jobs:
  alarm:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Webhook
        uses: comento/pr-alarm-to-agit-action@master
        with:
          url: ${{ secrets.AGIT_WEBHOOK_URL }}
          event: ${{ github.event.pull_request.url }}
          private: true
          token: ${{ secrets.TOKEN }}